name: "Say Hello"
description: "A simple composite action example"
inputs:
  name:
    description: "The name to greet"
    required: true
runs:
  using: "composite"
  steps:
    - name: Say Hello
      run: ./hello.sh "${{ inputs.name }}"
      shell: bash
